services:
  - type: web
    name: realdeli-tech-ai-bot
    env: python
    pythonVersion: "3.11.9"
    buildCommand: pip install --upgrade pip wheel && pip install -r requirements.txt --prefer-binary
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
